"""Generalized Knowledge Distillation (GKD) training primitives.

This module implements the paper Agarwal et al. 2023,
"On-Policy Distillation of Language Models: Learning from Self-Generated
Mistakes" (arXiv 2306.13649). The paper's method is the standard
meaning of "on-policy distillation" (OPD) in the literature.

What this module does NOT do
----------------------------

This module is *not* offline DPO. Offline DPO trains on a fixed JSONL
of preference pairs that were sampled and graded once, and lives in
``finpost.training.dpo`` / ``finpost.training.dpo_train``. GKD requires
a separate teacher model and uses a per-token divergence between
teacher and student distributions on student-sampled trajectories;
the loss has no preference-pair structure at all.

The math (Section 3.1 of the paper)
-----------------------------------

For a prompt x and a completion y of length L_y generated by the student,
the per-token divergence at each response position n is

    D(p_T || p_S^theta)(y | x) = (1 / L_y) sum_{n=1..L_y}
                                     D( p_T(. | y_{<n}, x) || p_S^theta(. | y_{<n}, x) ),

averaged over response positions. The unified GKD objective with
on-policy fraction lambda is

    L_GKD(theta) = (1 - lambda) E_{(x, y) ~ dataset}        [ D(p_T || p_S) on y ]
                 + lambda       E_{x ~ prompts, y ~ p_S}    [ D(p_T || p_S) on y ].

- lambda = 0: supervised KD on a fixed dataset of teacher outputs.
- lambda = 1: pure on-policy GKD. Paper recommends this across tasks.
- lambda in (0, 1): mixed.

Gradient flow (paper, Section 3.1, verbatim): "we do not backpropagate
through the student's sampling distribution... Not backpropagating
through the sampling makes the training stable and computationally
efficient." So the sampled tokens y are detached from the autograd
graph. Gradient flows only through the student's per-token
log-probabilities computed on the already-sampled sequence.

Sample-based reverse KL primitive
---------------------------------

This file currently implements reverse KL only. Reverse KL = JSD(beta -> 1)
in the paper's generalized JSD family. Its definition is

    KL( p_S || p_T )(y_t) = E_{v ~ p_S}[ log p_S(v) - log p_T(v) ]
                          = sum_v p_S(v) * (log p_S(v) - log p_T(v)).

Because the student already sampled exactly one token y_t from p_S at
each position during generation, we have a single-sample Monte Carlo
estimate of the expectation:

    KL_t ~= log p_S(y_t) - log p_T(y_t).

This estimator is unbiased over many positions in a batch and uses
ONLY per-token log-probabilities - the same quantity our existing
``token_log_probs_via_cross_entropy`` kernel produces. No full
distribution buffer is materialized, so memory cost is the same as
two cross_entropy forward passes (one student, one teacher).

Two estimator families live in this module:

1. **Sample-based reverse KL** (``reverse_kl_per_token``,
   ``gkd_reverse_kl_loss``). Uses the single token sampled from p_S
   during generation. Cheap: per-token log-probs only, no
   full-vocab buffer. Unbiased single-sample estimator of reverse
   KL on each response position.

2. **Full-distribution generalized JSD(beta)** (``jsd_beta_per_token``,
   ``gkd_jsd_loss``). Sums over the full vocabulary at each
   position. Materializes (B, S-1, V) tensors of log-probabilities
   for both teacher and student. More memory but exact. Covers the
   paper's three named divergences via one beta parameter:

       beta = 0.0  -> forward KL   = KL(p_T || p_S)   (mode-covering)
       beta = 0.5  -> symmetric JSD                   (bounded by log 2)
       beta = 1.0  -> reverse KL   = KL(p_S || p_T)   (mode-seeking)

   For 0 < beta < 1, M_beta = beta * p_T + (1 - beta) * p_S and

       JSD_beta(p_T || p_S) = beta * KL(p_T || M_beta)
                            + (1 - beta) * KL(p_S || M_beta).

Endpoint note: at exactly beta = 0 or beta = 1, the JSD formula
above collapses to 0 because M_beta equals one of the inputs and
that side's KL is 0 while the other side is scaled to 0. The paper
recovers KL via the scaled limit lim_{beta->0} JSD_beta / beta =
KL(p_T || p_S). We special-case beta = 0 and beta = 1 in
``jsd_beta_per_token`` to return the genuine forward and reverse KL
directly, which is what callers actually want when they ask for
"forward KL" or "reverse KL".

Paper-aligned defaults
----------------------

Arithmetic-reasoning result closest to FinChain: **forward KL** (beta = 0).
WMT En-De: JSD(beta = 0.1). Instruction tuning: reverse KL. XSum:
forward KL. The FinChain config picks a divergence from this menu; the
trainer reads ``beta`` from config and calls ``gkd_jsd_loss``.
"""

from __future__ import annotations

import math

import torch
import torch.nn.functional as F

from finpost.training.logprobs import token_log_probs_via_cross_entropy
from finpost.training.masking import IGNORE_INDEX


def reverse_kl_per_token(
    *,
    student_logits: torch.Tensor,
    teacher_logits: torch.Tensor,
    labels: torch.Tensor,
    ignore_index: int = IGNORE_INDEX,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Per-token sample-based reverse KL for GKD.

    Inputs:
        student_logits: shape ``(batch, seq, vocab)``. Logits from the
            student model on the (prompt + student-sampled completion)
            sequence. Computed WITH gradient enabled.
        teacher_logits: shape ``(batch, seq, vocab)``. Logits from the
            teacher model on the same sequence. Computed in
            ``torch.no_grad()``.
        labels: shape ``(batch, seq)``. Token IDs at response positions,
            ``IGNORE_INDEX`` at prompt and padding positions. Same
            convention as the SFT and DPO trainers. These are the
            tokens that were sampled from the student during
            ``generate()`` — they are the y_t values in the math above.
        ignore_index: positions where labels equal this are excluded.

    Returns:
        per_token_kl: shape ``(batch, seq - 1)``. ``log p_S(y_t) -
            log p_T(y_t)`` at response positions, exactly ``0.0`` at
            ignored positions. Gradient flows through the student
            term; teacher term is detached (caller is expected to
            have computed ``teacher_logits`` under ``no_grad``, but
            we also assert this is gradient-free).
        response_mask: shape ``(batch, seq - 1)`` of bool. ``True`` at
            response positions, ``False`` at ignored positions.

    Notes:
        - This is a SAMPLE-based estimator. It assumes the labels y_t
          were sampled from p_S during the student's generation
          pass. If you pass labels that were not student-sampled
          (e.g. teacher-generated completions), the resulting
          quantity is not reverse KL — it is per-token cross-entropy
          between student and teacher at those tokens. Don't do that
          unless you mean to.
        - The batch/sequence dimensions of ``student_logits`` and
          ``teacher_logits`` must match. If their vocab dimensions
          differ only because one model pads its LM head to a larger
          multiple, both tensors are truncated to the shared prefix
          vocabulary after checking that all real labels fit there.
          The GKD paper assumes a shared tokenizer/vocabulary; this
          padding alignment is only safe under that assumption.
    """
    student_logits, teacher_logits = _align_logits_for_shared_vocab(
        student_logits=student_logits,
        teacher_logits=teacher_logits,
        labels=labels,
    )

    if student_logits.shape != teacher_logits.shape:
        raise ValueError(
            "student and teacher logits must have the same shape; got "
            f"{tuple(student_logits.shape)} vs {tuple(teacher_logits.shape)}"
        )

    student_logps, response_mask = token_log_probs_via_cross_entropy(
        student_logits, labels, ignore_index=ignore_index
    )
    teacher_logps, _ = token_log_probs_via_cross_entropy(
        teacher_logits, labels, ignore_index=ignore_index
    )

    # Reverse KL estimator at the student-sampled tokens. The student
    # term carries grad; the teacher term must not, so we detach it
    # defensively even if the caller already set no_grad on the
    # teacher forward. Defense in depth.
    per_token_kl = student_logps - teacher_logps.detach()

    # token_log_probs_via_cross_entropy returns 0.0 at ignored
    # positions for both student and teacher, so per_token_kl is
    # exactly 0.0 at those positions — no separate masking needed
    # before averaging.
    return per_token_kl, response_mask


def gkd_reverse_kl_loss(
    *,
    student_logits: torch.Tensor,
    teacher_logits: torch.Tensor,
    labels: torch.Tensor,
    ignore_index: int = IGNORE_INDEX,
) -> tuple[torch.Tensor, dict[str, torch.Tensor]]:
    """Scalar GKD loss using sample-based reverse KL.

    Averages ``reverse_kl_per_token`` over response tokens. Returns a
    scalar suitable for ``loss.backward()`` and a small metrics dict
    for logging.

    The loss is the mean per-token reverse KL across the batch's
    response positions. Reverse KL is non-negative for true
    distributions but can be slightly negative under the single-
    sample estimator — that is expected variance, not a bug.
    """
    per_token_kl, response_mask = reverse_kl_per_token(
        student_logits=student_logits,
        teacher_logits=teacher_logits,
        labels=labels,
        ignore_index=ignore_index,
    )

    response_count = response_mask.sum()
    if response_count == 0:
        raise ValueError("GKD batch has no response tokens after masking")

    # Sum then divide by the count of response tokens. Equivalent to
    # mean over non-ignored positions; safe because per_token_kl is
    # already 0 at ignored positions.
    loss = per_token_kl.sum() / response_count

    detached_kl = per_token_kl.detach()
    metrics: dict[str, torch.Tensor] = {
        "loss": loss.detach(),
        "mean_kl": loss.detach(),
        "response_tokens": response_count.detach().float(),
        "max_per_token_kl": detached_kl.max(),
        "min_per_token_kl": detached_kl.min(),
    }
    return loss, metrics


def jsd_beta_per_token(
    *,
    student_logits: torch.Tensor,
    teacher_logits: torch.Tensor,
    labels: torch.Tensor,
    beta: float,
    sequence_chunk_size: int | None = None,
    ignore_index: int = IGNORE_INDEX,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Per-token generalized JSD(beta) divergence with the teacher
    detached from autograd.

    Special-cased endpoints:

        beta = 0.0  -> forward KL   = sum_v p_T(v) * (log p_T - log p_S)
        beta = 1.0  -> reverse KL   = sum_v p_S(v) * (log p_S - log p_T)
                                      (full-vocab exact form, not the
                                      single-sample estimator in
                                      ``reverse_kl_per_token``)
        0 < beta < 1: JSD_beta(p_T || p_S) using
                      M = beta * p_T + (1 - beta) * p_S.

    Inputs:
        student_logits: shape ``(batch, seq, vocab)``. WITH gradient.
        teacher_logits: shape ``(batch, seq, vocab)``. Computed under
            ``no_grad`` by the caller; we also ``.detach()`` the
            teacher log-softmax defensively.
        labels: shape ``(batch, seq)``. IGNORE_INDEX at prompt/padding,
            token IDs at response positions. The student-sampled
            sequence after concatenation with the prompt.
        beta: divergence interpolation in ``[0.0, 1.0]``.
        sequence_chunk_size: optional number of shifted sequence
            positions to process per log-softmax chunk. This preserves
            the exact loss while reducing the peak extra VRAM from
            O(batch * seq * vocab) to O(batch * chunk * vocab).

    Returns:
        per_token_div: shape ``(batch, seq - 1)``. The divergence at
            each response position, exactly ``0.0`` at ignored
            positions.
        response_mask: shape ``(batch, seq - 1)`` of bool.

    Notes:
        - Logits are promoted to float32 inside the function before
          the log_softmax, because summing over the vocabulary
          dimension at large V is accuracy-sensitive. The promotion
          is local; caller-side dtypes are not modified.
        - For 0 < beta < 1 we compute ``log_M`` via
          ``torch.logaddexp(log_p_T + log(beta), log_p_S +
          log(1-beta))`` which is the numerically stable form of the
          log of the linear mixture.
    """
    if not 0.0 <= beta <= 1.0:
        raise ValueError(f"beta must be in [0, 1]; got {beta}")
    if sequence_chunk_size is not None and sequence_chunk_size <= 0:
        raise ValueError("sequence_chunk_size must be positive when provided")
    if student_logits.ndim != 3:
        raise ValueError(
            f"logits must have shape (batch, seq, vocab); got {tuple(student_logits.shape)}"
        )
    if labels.ndim != 2:
        raise ValueError(f"labels must have shape (batch, seq); got {tuple(labels.shape)}")
    if student_logits.shape[:2] != labels.shape:
        raise ValueError(
            "logits and labels batch/sequence dimensions must match: "
            f"{tuple(student_logits.shape[:2])} vs {tuple(labels.shape)}"
        )
    if student_logits.size(1) < 2:
        raise ValueError("jsd_beta_per_token requires sequence length >= 2")
    student_logits, teacher_logits = _align_logits_for_shared_vocab(
        student_logits=student_logits,
        teacher_logits=teacher_logits,
        labels=labels,
    )

    # Causal-LM shift, same convention as token_log_probs_via_cross_entropy.
    shifted_student = student_logits[:, :-1, :]
    shifted_teacher = teacher_logits[:, :-1, :]
    shifted_labels = labels[:, 1:]
    response_mask = shifted_labels != ignore_index

    shifted_seq_len = shifted_student.size(1)
    if sequence_chunk_size is None or sequence_chunk_size >= shifted_seq_len:
        per_token_div = _jsd_beta_chunk(
            shifted_student=shifted_student,
            shifted_teacher=shifted_teacher,
            beta=beta,
        )
    else:
        div_chunks: list[torch.Tensor] = []
        for start in range(0, shifted_seq_len, sequence_chunk_size):
            end = min(start + sequence_chunk_size, shifted_seq_len)
            div_chunks.append(
                _jsd_beta_chunk(
                    shifted_student=shifted_student[:, start:end, :],
                    shifted_teacher=shifted_teacher[:, start:end, :],
                    beta=beta,
                )
            )
        per_token_div = torch.cat(div_chunks, dim=1)

    # Zero out ignored positions explicitly. (Even though the
    # log_softmax produced finite values there, the divergence at
    # those positions is meaningless because the labels mark them
    # as prompt or padding.)
    per_token_div = per_token_div * response_mask
    return per_token_div, response_mask


def _align_logits_for_shared_vocab(
    *,
    student_logits: torch.Tensor,
    teacher_logits: torch.Tensor,
    labels: torch.Tensor,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Align models whose LM heads differ only by padded vocab rows.

    Qwen checkpoints from different sizes can share tokenizer IDs while
    padding their output matrices to different multiples. GKD is defined
    over a shared vocabulary, so extra rows beyond the shared prefix are
    discarded and the distributions are renormalized over common token IDs.
    """
    if student_logits.ndim != 3 or teacher_logits.ndim != 3:
        raise ValueError(
            "student and teacher logits must have shape (batch, seq, vocab); got "
            f"{tuple(student_logits.shape)} vs {tuple(teacher_logits.shape)}"
        )
    if student_logits.shape[:2] != teacher_logits.shape[:2]:
        raise ValueError(
            "student and teacher logits batch/sequence dimensions must match; got "
            f"{tuple(student_logits.shape)} vs {tuple(teacher_logits.shape)}"
        )
    if student_logits.size(-1) == teacher_logits.size(-1):
        return student_logits, teacher_logits

    shared_vocab_size = min(student_logits.size(-1), teacher_logits.size(-1))
    real_labels = labels[labels != IGNORE_INDEX]
    if real_labels.numel() > 0 and int(real_labels.max().item()) >= shared_vocab_size:
        raise ValueError(
            "labels contain token IDs outside the shared student/teacher vocabulary; "
            f"max label id {int(real_labels.max().item())}, shared vocab size "
            f"{shared_vocab_size}"
        )
    return (
        student_logits[..., :shared_vocab_size],
        teacher_logits[..., :shared_vocab_size],
    )


def _jsd_beta_chunk(
    *,
    shifted_student: torch.Tensor,
    shifted_teacher: torch.Tensor,
    beta: float,
) -> torch.Tensor:
    """Compute JSD(beta) for an already-shifted sequence chunk."""
    # Promote to float32 for the KL sums. Vocab-dim reductions on
    # bf16/fp16 lose enough precision that very small probabilities
    # can underflow and accumulate bias. Chunking over sequence
    # positions keeps that precision without materializing the whole
    # sequence's log-probability tensor at once.
    log_p_S = F.log_softmax(shifted_student.float(), dim=-1)
    log_p_T = F.log_softmax(shifted_teacher.float(), dim=-1).detach()

    if beta == 0.0:
        # Forward KL: KL(p_T || p_S) = sum_v p_T(v) * (log p_T - log p_S).
        per_token_div = (log_p_T.exp() * (log_p_T - log_p_S)).sum(dim=-1)
    elif beta == 1.0:
        # Exact reverse KL (NOT the sample-based estimator above).
        per_token_div = (log_p_S.exp() * (log_p_S - log_p_T)).sum(dim=-1)
    else:
        log_beta = math.log(beta)
        log_one_minus_beta = math.log(1.0 - beta)
        # log of the mixture M = beta * p_T + (1 - beta) * p_S.
        # torch.logaddexp(a, b) = log(exp(a) + exp(b)), numerically stable.
        log_M = torch.logaddexp(
            log_p_T + log_beta,
            log_p_S + log_one_minus_beta,
        )
        kl_T_M = (log_p_T.exp() * (log_p_T - log_M)).sum(dim=-1)
        kl_S_M = (log_p_S.exp() * (log_p_S - log_M)).sum(dim=-1)
        per_token_div = beta * kl_T_M + (1.0 - beta) * kl_S_M

    return per_token_div


def gkd_jsd_loss(
    *,
    student_logits: torch.Tensor,
    teacher_logits: torch.Tensor,
    labels: torch.Tensor,
    beta: float,
    sequence_chunk_size: int | None = None,
    ignore_index: int = IGNORE_INDEX,
) -> tuple[torch.Tensor, dict[str, torch.Tensor]]:
    """Scalar GKD loss using full-distribution generalized JSD(beta).

    Averages ``jsd_beta_per_token`` over response tokens. Returns the
    scalar loss and a metrics dict for logging. Use this when you
    want the paper-faithful divergence at the cost of a (B, S-1, V)
    log-probability buffer per model.
    """
    per_token_div, response_mask = jsd_beta_per_token(
        student_logits=student_logits,
        teacher_logits=teacher_logits,
        labels=labels,
        beta=beta,
        sequence_chunk_size=sequence_chunk_size,
        ignore_index=ignore_index,
    )

    response_count = response_mask.sum()
    if response_count == 0:
        raise ValueError("GKD batch has no response tokens after masking")

    loss = per_token_div.sum() / response_count

    detached_div = per_token_div.detach()
    metrics: dict[str, torch.Tensor] = {
        "loss": loss.detach(),
        "mean_jsd": loss.detach(),
        "beta": torch.tensor(beta, dtype=torch.float32),
        "response_tokens": response_count.detach().float(),
        "max_per_token_div": detached_div.max(),
        "min_per_token_div": detached_div.min(),
    }
    return loss, metrics
